# Generated by Django 4.2.1 on 2023-06-07 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_fild',
            new_name='phone_field',
        ),
    ]
